### ISSUE TITLE
Merge points & check-in pages

### ISSUE THREAD

**Issue by gracewzhang** [IllinoisWCS/points-frontend#9]
### Overview
- The points component should look similar to how it does now except it'll take up the bottom half of the check-in page
- After checking in, the points component should rerender & display the event you just checked in for
- The points component should have a border & header (the header being "Points") similar to the "Event key" box
    - The body should be the list of events like what you see right now (keep it as is)
    - The component should be scrollable, not the page (so there's a scrollbar within the component)

### Guidelines/Tips
- Start by extracting check-in & points into separate components (so they're no longer pages)
    - The Check-In component is just the box containing the "Event key" header + input + button
- Rename the Check-In page to Home
- Home should contain the Check-In and Points components you extracted
- Your best frame of reference is the other components in the repo!

**Comment by 3sannasia** [comment]
Modifications made based on comments:

add "home" header outside of the 2 boxes
rename "home" in the check in box to "check in"
increased spacing between check in & points boxes
Made home bigger than the check in and points heading

<img width="1440" alt="Screenshot 2023-04-11 at 5 54 13 PM" src="https://user-images.githubusercontent.com/54860072/231306006-5d01978d-84f8-423b-a7e1-98e099b00ab2.png">

Checked dark mode functionality as well: 

<img width="1440" alt="Screenshot 2023-04-11 at 5 54 02 PM" src="https://user-images.githubusercontent.com/54860072/231306020-0d0d5723-c1b1-41b1-b870-3a6772a9e83c.png">
